=== mohandayman/project-XML/employee.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT employees (employee*)>
<!ELEMENT employee (name, phones, addresses,email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT addresses (address+)>
<!ELEMENT address (city,street,region,buildingNo)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT buildingNo (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST phone type CDATA #REQUIRED>

=== mohandayman/project-XML/lab1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet type="text/css" href="style.css"?>-->
<!--<!DOCTYPE employees SYSTEM "employee.dtd">-->
<?xml-stylesheet type="text/xsl" href="style.xsl"?>

<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/mohand/Desktop/XML%20files/schema.xsd">
	<employee>
		<name>mohand ayman</name>
		<phones>
			<phone type="mobile">0125488878</phone>
			<phone type="home">87765</phone>
		</phones>
		<addresses>
			<address>
				<city>Alex</city>
				<street>daramaly</street>
				<region>bahary></region>
				<buildingNo>120</buildingNo>
			</address>
		</addresses>
		<email>mohandayman0127gmail.com</email>
	</employee>
	<employee>
		<name>osama alaa</name>
		<phones>
			<phone type="mobile">897897</phone>
		
		</phones>
		<addresses>
			<address>
				<city>Alex</city>
								

				<street>Elhoe]rreya</street>
				<region>Sporting></region>
				<buildingNo>103</buildingNo>
			</address>
		</addresses>
		<email>mohandayman0127gmail.com</email>
	</employee>
	
</employees>
